version: '3.7'

services:
  
  consul-server1:
    image: hashicorp/consul:1.10.1
    container_name: consul-server1
    hostname: consul-server1
    restart: always
    environment:
      VAULT_ADDR: "http://vault-server:8200"
      VAULT_TOKEN: "vault-plaintext-root-token"
      CONSUL_HTTP_ADDR: "consul-server1:8500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    cap_add:
      - IPC_LOCK
    volumes:
     - ./server1.json:/consul/config/server1.json
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul:1.10.1
    container_name: consul-server2
    hostname: consul-server2
    restart: always
    volumes:
     - ./server2.json:/consul/config/server2.json
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul:1.10.1
    container_name: consul-server3
    hostname: consul-server3
    restart: always
    volumes:
     - ./server3.json:/consul/config/server3.json
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.10.1
    container_name: consul-client
    hostname: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json
     - ./certs/:/consul/config/certs/:ro
     - ./tokens/:/consul/config/tokens/
    networks:
      - consul
    command: "agent"

  vault-server:
    image: hashicorp/vault:latest
    container_name: vault-server
    hostname: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://vault-server:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token" 
      CONSUL_HTTP_ADDR: "consul-server1:8500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    cap_add:
      - IPC_LOCK
    volumes:
     - ./payloads/:/payloads/
    networks:
      - consul

networks:
  consul:
    driver: bridge